name: Changeset Check

on:
  pull_request:
    branches: ["main"]

jobs:
  towncrier:
    if: ${{ !contains(join(github.event.pull_request.labels.*.name, ','), 'skip-changelog') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Validate Towncrier fragments
        run: |
          uvx towncrier build --draft --version 0.0.0
